service: product-service
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs14.x
  httpApi:
    cors:
      allowedOrigins:
        - https://d3nui0d4pbm0dk.cloudfront.net
  environment:
    PRODUCTS_TABLE: CloudX_Products
    STOCKS_TABLE: CloudX_Stocks
    SNS_REGION: eu-west-3
    SNS_TOPIC_ARN: !Ref productsDBUpdated
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:eu-west-3:233065634700:table/CloudX_Products"
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:eu-west-3:233065634700:table/CloudX_Stocks"
        - Effect: Allow
          Action:
            - sqs:CreateQueue
            - sqs:ReceiveMessage
          Resource: 
            Fn::GetAtt: [ catalogItemsQueue, Arn ]
        - Effect: "Allow"
          Resource: "*"
          Action:
            - "sns:*"            
  stage: dev
  region: eu-west-3
functions:
  getProductsList:
    handler: handlers/getProductsList.handler
    events:
      - httpApi:
          path: /products
          method: get
  getProductsById:
    handler: handlers/getProductsById.handler
    events:
      - httpApi:
          path: /products/{productId}
          method: get
  createProduct:
    handler: handlers/createProduct.handler
    events:
      - httpApi:
          path: /products
          method: post
  catalogBatchProcess:
    handler: handlers/catalogBatchProcess.handler
    events:
      - sqs:
          arn: arn:aws:sqs:eu-west-3:233065634700:catalogItemsQueue
          batchSize: 5
resources:
  Resources:
    catalogItemsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue
    productsDBUpdated:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: productsDBUpdated
    productsDBUpdatedTopicSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: vitaliibaryliuk@gmail.com
        Protocol: email
        TopicArn:
          Ref: productsDBUpdated

