service: authorization-service
plugins:
  - serverless-dotenv-plugin
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-3
functions:
  basicAuthorizer:
    handler: handlers/basicAuthorizer.handler
resources:
  Outputs:
    authorizationArn:
      Value: arn:aws:lambda:eu-west-3:233065634700:function:authorization-service-dev-basicAuthorizer